apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  zones: ap-northeast-2a
reclaimPolicy: Retain
mountOptions:
  - debug
